Fix for hopper dump after refill
MisoRobotics/miso_peripherals pull request #60
Opened 2020-10-17 20:28 UTC by luke-powers

Adds calibrations and adjusts code to use config management system.

https://github.com/MisoRobotics/config-management-manual-edits/pull/249
https://github.com/MisoRobotics/chippy/pull/1182

2020-10-17 20:42 UTC, rsinnet commented on miso_peripherals/launch/ram_hopper_node.launch
> +    device: /dev/ttyACM0,
Can we use `/dev/numato` instead please? The udev rules are installed on both spaceship systems.

2020-10-17 20:43 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +    REFILL_BAG = 2268.
This should really be like 5 lbs which is 11,025 g.

2020-10-17 20:44 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +    MAX_WEIGHT = 13608.
This should correspond to the mass that the hopper can hold, which I believe is 30 lbs or 66,150 g. @r-anderson-20 @abhibhakuni  is that correct?

2020-10-18 16:19 UTC, luke-powers commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +    REFILL_BAG = 2268.
1 lb = 453.59237 g, 5 lb × 453.59237 = 2268 g. https://en.wikipedia.org/wiki/Pound_(mass), https://www.google.com/search?&q=lbs+to+grams&oq=lbs+to+grams

2020-10-18 16:20 UTC, luke-powers commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +    MAX_WEIGHT = 13608.
See above.

2020-10-18 16:25 UTC, luke-powers commented on miso_peripherals/launch/ram_hopper_node.launch
> +    device: /dev/ttyACM0,
Updated.

2020-10-20 07:52 UTC, luke-powers commented
This has been tested in dev and works as expected.

2020-10-20 12:56 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +    REFILL_BAG = 2268.
Oh god I uses 2205 instead of 454. Thanks. 🙈

2020-10-20 12:57 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +    MAX_WEIGHT = 13608.
Oops wrong conversion number.

2020-10-20 13:12 UTC, rsinnet requested changes
Just requesting a change to the test case. Other comments can be ignored.

One thing I noticed is that there is some code churn throughout the commits that doesn't show up in the squashed diff. It would be a bit faster to review if the code churn could be eliminated by autosquashing at some appropriate point in time, though admittedly that's not always possible. Note that this is a general comment and can be ignored for this review since it's only a few lines and I've already reviewed it.

2020-10-20 13:12 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +        # NOTE(LCP): Values are in grams.
I think we should leave the previous note as well so no one has to guess where these come from.

2020-10-20 13:12 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/controller.py
> +    _DEVICE = 'device'
Don't need a blank line above this.

2020-10-20 13:12 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/controller.py
> +            hopper_params (dict): Params for the Numato including:
I'm really not a fan of structure being imposed this way, but let's not address my concern now.

2020-10-20 13:12 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +
Blank line should be removed here. The reason you sometimes see it is because class member function definitions must have a blank line before and after, but this rule does not apply member variables in PEP 8. LMK if I'm wrong about this.

2020-10-20 18:19 UTC, luke-powers commented on miso_peripherals/test/test_ram_hopper.py
> +        for i in range(int(bin_.MAX_WEIGHT)):
Really it should be `bin_.weight+1`. That was what was done with the above test. I've changed it to match that.

2020-10-20 18:20 UTC, luke-powers commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +        # NOTE(LCP): Values are in grams.
These comments were intended to be moved to https://github.com/MisoRobotics/config-management-manual-edits/pull/258 I'll make sure it gets updated there.

2020-10-20 18:20 UTC, luke-powers commented on miso_peripherals/src/miso_peripherals/hopper/controller.py
> +    _DEVICE = 'device'
Updated.

2020-10-20 18:20 UTC, luke-powers commented on miso_peripherals/src/miso_peripherals/hopper/driver.py
> +
Updated.

2020-10-20 18:21 UTC, luke-powers commented on miso_peripherals/src/miso_peripherals/hopper/controller.py
> +            hopper_params (dict): Params for the Numato including:
It's worth discussing what you'd prefer even if it doesn't get into this PR.

2020-10-20 21:58 UTC, Schwo0ps approved these changes

2020-10-20 21:58 UTC, Schwo0ps commented on miso_peripherals/launch/ram_hopper_node.launch
> +      pin_config: [6, 1, 7, 10, 13, 344., -899.],
Why do only the last 2 numbers have a decimal?

2020-10-20 21:58 UTC, Schwo0ps commented on miso_peripherals/src/miso_peripherals/hopper/controller.py
> +            hopper_params (dict): Params for the Numato including:
He probably means using a NamedTuple or object class. -- though asserts checking for valid data would do the same.

2020-10-21 01:02 UTC, rsinnet commented on miso_peripherals/launch/ram_hopper_node.launch
> +      pin_config: [6, 1, 7, 10, 13, 344., -899.],
I think they are used in division possibly to convert from voltage to weight.

2020-10-21 01:03 UTC, rsinnet approved these changes

2020-10-21 01:04 UTC, rsinnet approved these changes

2020-10-21 01:04 UTC, rsinnet commented on miso_peripherals/src/miso_peripherals/hopper/controller.py
> +            hopper_params (dict): Params for the Numato including:
I like a data structure that can contain the documentation. Self-contained. @ludwig showed me once how to add docstrings to a `namedtuple`.

2020-10-21 05:22 UTC, luke-powers commented
Squashed and rebased.

2020-10-21 18:58 UTC, zzv2 approved these changes

2020-10-21 18:58 UTC, merged